# Generated by Django 4.1 on 2022-08-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_scopes_article_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='ArticleTag',
        ),
    ]
